language: cpp
compiler: gcc
dist: trusty
sudo: required
matrix:
  include:
  - env: TARGET_OS=
#  - env: TARGET_OS=win32
  - env: TARGET_OS=win64
  - os: osx
before_install:
- "$TRAVIS_BUILD_DIR/travis/$TRAVIS_OS_NAME.$TARGET_OS.before_install"
install:
- "$TRAVIS_BUILD_DIR/travis/$TRAVIS_OS_NAME.$TARGET_OS.install"
script:
- "$TRAVIS_BUILD_DIR/travis/$TRAVIS_OS_NAME.$TARGET_OS.script"
deploy:
  provider: releases
  api_key:
    secure: AHrZrDfRp7rXCt/cRq+KdZMHUWc3tBnsF36f0gsC8Pmd/0LsyhcE8vSfejgyeiZP+2VEcUkMcAxlI7VaPHuibJXXchQ6lno9mljo7E8DDErOr1gAPqTf4eG/8rGo/2oEHUaM/TH94avylXtVY7q+FDzhD30hCmPyYWS5V6txB/KYdL4RLWKTM1lOz4vobvuDzhPj6gKKCXUlmzQWwt3LCyMhMeZ5yDayd3jOC2UN6gtV3Hl/kpttHv1eXrO2ySBvMaf9Y1P0CdgOzqRAzbhoU1hYiy31eA+behR+CEZV0Rb5rxx068WermH8/+/OEYhx9WQ6H5JDboAzFq3paVdpmrQ8YPO6jNHjo5OmnzCieuTNndw1i8Aj4SHw7S4Z4yYYMe462xjYz/kTS6pdWoZMJL+MYblZbqeBzVqCHte1YWhd5QbQ/ugCh+VBXM6VxGVnbvknzGUHdG7vVw0VGaEbzUcf9SCnde3QpwtKxDbl4aX5pGRFdGg1mTCltfm3Ct9bgYipAScmuHBrvBFnL6ICgj0cYm876/OplOzMOUPC8YZD3rdOAs+iqbRomNqXQPI5CA1ezV/wnTbTs7jqVgCm+BQSnnoBo3s3scrAAeJwhRqdKeZpMSBUhH9xwwORZrmUenlC70i//MA7QIB3Ml3Oyjx+v3qh7ZZR+GOAs3tJ/7Y=
  file_glob: true
  file:
  - signtextjs_plus-${TRAVIS_TAG:1}-*.run
  - signtextjs_plus-${TRAVIS_TAG:1}-*.exe
  - signtextjs_plus-${TRAVIS_TAG:1}-*.dmg
  - embedded-libs-${TRAVIS_TAG:1}-linux-source.tar.xz
  - embedded-libs-${TRAVIS_TAG:1}-windows-source.tar.xz
  - embedded-libs-${TRAVIS_TAG:1}-macos-source.tar.xz
  skip_cleanup: true
  on:
    tags: true
    repo: jasp00/signTextJS
