#!/bin/sh
set -e

if [ ! -e nssdb ]
then
	PATH="$PATH${PATH:+:}/usr/local/opt/nss/bin" ../setup-nssdb
fi

MOZ_CRASHREPORTER_EVENTS_DIRECTORY="$PWD/nssdb/crashes/events" \
	./test ../../src/macos/signtextjs_plus
