#!/bin/sh
set -e
TOPDIR="$1"
RUNFILE="$2"
[ "$TOPDIR" -a "$RUNFILE" ]

TOPDIR="$(readlink -e "$TOPDIR")"

cd "$TOPDIR"
[ -e src/linux/signtextjs_plus ]

rm -fr installer.root
mkdir installer.root
cd installer.root

install "$TOPDIR"/src/linux/signtextjs_plus .
install -m 644 "$TOPDIR"/src/signtextjs_plus.json .
install "$TOPDIR"/installer/linux/installer .

strip signtextjs_plus

cd ..
makeself --xz --complevel 6 installer.root "$RUNFILE" "signTextJS plus" \
	./installer
