#!/bin/sh
set -e

if [ $(id -u) -eq 0 ]
then
	DIR=/usr/lib/mozilla/native-messaging-hosts
	umask 022
	chown 0:0 *
else
	DIR="$HOME"/.mozilla/native-messaging-hosts
	sed -e "s#/usr/lib/mozilla/native-messaging-hosts#$DIR#" -i \
		signtextjs_plus.json
fi
echo Installing to "$DIR"
mkdir -p "$DIR"

mv signtextjs_plus \
	signtextjs_plus-bin \
	signtextjs_plus.json \
	libjsoncpp.so.0 \
	"$DIR"
