#!/bin/sh
set -e
TOPDIR="$1"
VERSION="$2"
[ "$TOPDIR" -a "$VERSION" ]

TOPDIR="$(greadlink -e "$TOPDIR")"

cd "$TOPDIR"
[ -e src/macos/signtextjs_plus ]

rm -fr installer.root
mkdir installer.root
cd installer.root

install -m 644 "$TOPDIR"/src/signtextjs_plus.json .
mkdir signtextjs_plus.app
cd signtextjs_plus.app
install "$TOPDIR"/src/macos/signtextjs_plus .
install -m 644 \
	$(otool -l signtextjs_plus |
		grep -Eo "/usr/local/opt/jsoncpp/lib/libjsoncpp.*dylib") \
	/usr/local/opt/nspr/lib/libnspr4.dylib \
	/usr/local/opt/nspr/lib/libplc4.dylib \
	/usr/local/opt/nspr/lib/libplds4.dylib \
	/usr/local/opt/nss/lib/*.dylib \
	.
for FILE in signtextjs_plus *.dylib
do
	DYLIBS="$(otool -l $FILE | grep -Eo "/usr/local/.*dylib" || true)"
	for DYLIB in $DYLIBS
	do
		REL=${DYLIB##*/}
		if [ "$REL" = "$FILE" ]
		then
			continue
		fi
		install_name_tool -change $DYLIB @executable_path/$REL $FILE
	done
done
MOZ_CRASHREPORTER_EVENTS_DIRECTORY="$TOPDIR"/test/macos/nssdb/crashes/events \
	"$TOPDIR"/test/macos/test ./signtextjs_plus
cd ..

LINUXDIR=/usr/lib/mozilla/native-messaging-hosts
MACOSDIR="/Library/Application Support/Mozilla/NativeMessagingHosts\
/signtextjs_plus.app"
sed -i .bak "s#$LINUXDIR#$MACOSDIR#" signtextjs_plus.json

cd ..
. ~/.nvm/nvm.sh
nvm install --lts
DMGFILE=signtextjs_plus-"$VERSION"-macos.dmg
appdmg installer/macos/package.json "$DMGFILE"

SOURCEDIR=embedded-libs-"$VERSION"-macos-source
rm -fr "$SOURCEDIR"
mkdir "$SOURCEDIR"
cd "$SOURCEDIR"

brew fetch -s jsoncpp nspr nss
for FILE in "$HOME"/Library/Caches/Homebrew/downloads/*
do
	case "$FILE" in
	*.bottle.*)
		continue
		;;
	esac
	cp -a "$FILE" .
done

cd ..
tar Jcf "$SOURCEDIR".tar.xz "$SOURCEDIR"
