#!/bin/sh
set -e
TOPDIR="$1"
VERSION="$2"
[ "$TOPDIR" -a "$VERSION" ]

TOPDIR="$(readlink -e "$TOPDIR")"

cd "$TOPDIR"
[ -e src/win64/signtextjs_plus.exe ]

rm -fr installer.root
mkdir installer.root
cd installer.root

install "$TOPDIR"/src/win64/signtextjs_plus.exe .
install -m 644 "$TOPDIR"/src/signtextjs_plus.json .

LINUXAPP=/usr/lib/mozilla/native-messaging-hosts/signtextjs_plus
WINAPP=signtextjs_plus.exe
sed -i "s#$LINUXAPP#$WINAPP#" signtextjs_plus.json

"$TOPDIR"/installer/win64/copy-dlls

x86_64-w64-mingw32-strip *.exe *.dll

cd ..
INSTFILE=signtextjs_plus-"$VERSION"-x86_64-w64-mingw32.exe
makensis -NOCD "-XOutFile $INSTFILE" installer/win64/script.nsi

SOURCEDIR=embedded-libs-"$VERSION"-windows-source
rm -fr "$SOURCEDIR"
mkdir "$SOURCEDIR"
cd "$SOURCEDIR"

apt-get -d source dlfcn-win32 gcc-mingw-w64 libjsoncpp-mingw-w64 mingw-w64 \
	nspr-mingw-w64 nss-mingw-w64 sqlite3-mingw-w64

cd ..
tar Jcf "$SOURCEDIR".tar.xz "$SOURCEDIR"
